### ISSUE TITLE
Accessibility and HTML validation

### ISSUE THREAD

**Issue by stullesha** [wjh18/hugo-liftoff#10]
**Is your feature request related to a problem? Please describe.**
Your theme throws a few accessibility warnings and errors / and some HTML warnings.

**Describe the solution you'd like**
Test your demo site with the "WAVE Evaluation Tool" extension (e.g. on a Chrome based browser) and https://validator.w3.org/ and  see the results.

**Comment by wjh18** [comment]
Thank you for reporting. I'll take a look at it and fix the most pressing errors. For contrast issues, sometimes those are unavoidable (for example with code highlighting) but I'll use my best judgement there.

**Comment by wjh18** [comment]
This PR should fix most of the a11y issues. I will update the theme on the example site. If I missed anything let me know and I can re-open.
