### ISSUE TITLE
Enable SCSS Sourcemap

### ISSUE THREAD

**Issue by RoneoOrg** [wjh18/hugo-liftoff#12]
**Is your feature request related to a problem? Please describe.**

Debugging the CSS generated by Hugo could be easier with a [sourcemap](https://gohugo.io/hugo-pipes/scss-sass/) pointing to the corresponding SCSS file

Here is a short note about implementing such a feature:

**Before:**

    {{ $normalizeSass := resources.Get "normalize.scss" }}
    {{ $normalizeStyle := $normalizeSass | resources.ToCSS  | resources.Fingerprint }}

**After:**

    {{ $options := (dict "enableSourceMap" true ) }}

    {{ $normalizeSass := resources.Get "normalize.scss" }}
    {{ $normalizeStyle := $normalizeSass | resources.ToCSS $options | resources.Fingerprint }}

What do you think?

(Thanks for this lovely theme BTW!)

**Comment by wjh18** [comment]
Thanks - I agree this would be good to have. I'll look into getting it added on the next update.

**Comment by wjh18** [comment]
Update: I'm not sure if this is even possible if using PostCSS processing. See https://github.com/gohugoio/hugo/issues/6189

I'm trying to find a workaround but in my tests the sourcemap is not being applied.
