### ISSUE TITLE
Disable Projects

### ISSUE THREAD

**Issue by condio** [wjh18/hugo-liftoff#16]
Was going to see if I could remove projects easily. Must have been missing something obvious. No worries.

**Comment by wjh18** [comment]
My bad, I was going to get to this. I don't have time to make the template changes necessary for this at the moment unfortunately. The theme was originally planned for use with projects so there wasn't much foresight on my end for disabling them (it'll require multiple template changes). I may consider accepting pull requests that implement it but like I said, don't have the time at the moment. Thanks for checking out the theme.
