### ISSUE TITLE
Insert image insie post 

### ISSUE THREAD

**Issue by pipMinder00** [wjh18/hugo-liftoff#23]
I try to insert image and adjust the size of it with markdown as follow 
![alt text](image URL){: width="50%"} 
but not work 
I tried as well HTML tag img not worked, any suggestion ? 

Thanks in advance

**Comment by wjh18** [comment]
You should be able to add CSS classes to images in markdown with URL fragments in the markdown image URL. This is processed via the image markdown render hook in `hugo-liftoff/layouts/_default/_markup/render-image.html`.

```markdown
![alt text](image.png#class)
```

Then in `assets/custom.css` in your project:
```
.class {
    width: 50%;
}
```

Alternatively you could use a [figure shortcode](https://gohugo.io/content-management/shortcodes/#figure) and add a `style` or `class` attribute from there.

**Comment by pipMinder00** [comment]
that works! thank you
