### ISSUE TITLE
Add Mastodon to social links

### ISSUE THREAD

**Issue by riussi** [wjh18/hugo-liftoff#25]
**Is your feature request related to a problem? Please describe.**
Missing Mastodon from Social links.

**Describe the solution you'd like**
Could you add Mastodon to the social links with the SVG-icon please?

**Describe alternatives you've considered**
I have a fork of your repo where I made the change for myself but would rather follow your main repo.
https://github.com/wjh18/hugo-liftoff/compare/master...riussi:hugo-liftoff:master

**Additional context**

**Comment by wjh18** [comment]
Will do. You can also override `social-links.html` in your own project's `layouts` in the meantime if that's easier. I'll update the SVGs sometime next week, been meaning to add more anyway.
