### ISSUE TITLE
Request: linking example site on https://themes.gohugo.io/themes/hugo-liftoff/

### ISSUE THREAD

**Issue by jamesbraza** [wjh18/hugo-liftoff#26]
I think this is a cool theme, just had a tough time finding the [demo website's link](https://hugo-liftoff.netlify.app/projects/). For example, [this theme](https://themes.gohugo.io/themes/hugo-story/) makes finding the demo easy.

Can you link it in the `README`, so its link also shows up on [the theme's page](https://themes.gohugo.io/themes/hugo-liftoff/)?

That way, it's easy to find the example site right away

**Comment by wjh18** [comment]
I can add it to the README, sure. I think that's a good idea regardless of the theme page.

There is also a yellow button that links to the demo on the theme page. That white text on yellow bg doesn't contrast very well.

<img width="1732" alt="Screenshot 2023-07-23 at 10 33 28 PM" src="https://github.com/wjh18/hugo-liftoff/assets/18322034/f9a2243d-9f39-4456-a2ac-32b592f06000">

**Comment by jamesbraza** [comment]
Oh wow, I missed that Demo button indeed.  In fact, I missed it on all the Hugo themes I have ever viewed! 🤣

**Comment by jamesbraza** [comment]
Thank you!
